version: '2'
services:
  web:
    build: ./webapp
    ports:
      - "80"
      - "3000"
      - "22"
    environment:
     - MYSQL_SERVER=mysql
    depends_on:
      - memcached
      - mysql
      - selenium-chrome
      - selenium-chrome-debug
    volumes:
      - ./webapp/:/var/www/html/

  memcached:
    image: memcached

  mysql:
    build: ./mysql
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/storage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
       - 80
    volumes:
       - /sessions

  selenium-chrome:
    image: selenium/standalone-chrome:3.4.0-chromium
    ports:
      - "4444"
    volumes:
      - /dev/shm:/dev/shm
      
  selenium-chrome-debug:
    image: selenium/standalone-chrome-debug:3.4.0-chromium
    ports:
      - "4444"
      - "5900"
    volumes:
      - /dev/shm:/dev/shm
