version: '2'
services:
  php:
    build: ./php
    ports:
      - "8000:80"
      - "3000:3000"
    environment:
     - MYSQL_SERVER=db
    depends_on:
      - memcached
      - mysql
    volumes:
      - /srv/docker/phpbase/src/:/var/www/html/

  memcached:
    image: memcached    

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /srv/docker/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
       - 8880:80
    volumes:
       - /sessions